# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
# Default language
en:
  languageCode: en
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
de:
  languageCode: de-DE
  contentDir: content/de
  title: Julius Stoll
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
